name: DeleteCrashDump
main: MineBlock\DeleteCrashDump\DeleteCrashDump
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 deletecrashdump:
  permission: deletecrashdump.cmd
  description: DeleteCrashDump
  usage: /DeleteCrashDump

permissions:
 deletecrashdump.cmd:
  default: op
  description: DeleteCrashDump - Command