name: CutMap
main: MineBlock\CutMap\CutMap
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 cutmap:
  permission: cutmap.cmd
  description: CutMap
  usage: /CutMap

permissions:
 cutmap.cmd:
  default: op
  description: MineBlock - CutMap - Command