name: ShowMoney
main: MineBlock\ShowMoney\ShowMoney
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 showmoney:
  permission: showmoney.cmd
  description: ShowMoney - Command
  usage: /ShowMoney

permissions:
 showmoney.cmd:
  default: op
  description: ShowMoney - Command