name: ClearEntities
main: MineBlock\ClearEntities\ClearEntities
version: "1.1"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 clearentities:
  permission: clearentities.cmd
  description: ClearEntities
  usage: /ClearEntities <All|Item|Arrow|Mob> <View|Clear>

permissions:
 clearentities.cmd:
  default: op
  description: ClearEntities - Command