name: MoneyNick
main: MineBlock\MoneyNick\MoneyNick
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 moneynick:
  permission: moneynick.cmd
  description: MoneyNick - Command
  usage: /MoneyNick

permissions:
 moneynick.cmd:
  default: op
  description: MoneyNick - Command