name: ChestView
main: MineBlock\ChestView\ChestView
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 chestview:
  permission: chestview.cmd
  description: ChestView
  usage: /ChestView

permissions:
 chestview.cmd:
  default: op
  description: ChestView - Command