name: SortInventory
main: MineBlock\SortInventory\SortInventory
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 SortInventory:
  permission: sortinventory.cmd
  description: SortInventory - Command
  usage: /SortInventory <View|Clear>

permissions:
 sortinventory.cmd:
  default: true
  description: SortInventory - Command