name: JoinCount
main: MineBlock\JoinCount\JoinCount
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 joincount:
  permission: joincount.cmd
  description: JoinCount
  usage: /JoinCount <View|Rank|Clear|AllClear>

permissions:
 joincount.cmd:
  default: op
  description: JoinCount - Command