name: Fishing
main: MineBlock\Fishing\Fishing
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 fishing:
  permission: fishing.cmd
  description: Fishing
  usage: /Fishing <Fishing|Rod|Bait|Delay|Cool|Count|Fishs>

permissions:
 fishing.cmd:
  default: op
  description: Fishing - Command