name: Gun
main: MineBlock\Gun\Gun
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 gun:
  permission: gun.cmd
  description: Gun
  usage: /Gun <Gun|Bullet|Cool>

permissions:
 gun.cmd:
  default: op
  description: Gun - Command