name: Prefix
main: MineBlock\Prefix\Prefix
version: "1.2"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 prefix:
  permission: prefix.cmd
  description: Prefix - Command
  usage: /Prefix <PlayerName> <Prefix>

permissions:
 prefix.cmd:
  default: op
  description: Prefix - Command