name: BanCraft
main: MineBlock\BanCraft\BanCraft
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 bancraft:
  permission: bancraft.cmd
  description: BanCraft
  usage: /BanCraft <Add|Del|Reset|List|Load>

permissions:
 bancraft.cmd:
  default: op
  description: BanCraft - Command
 bancraft.craft:
  default: op
  description: BanCraft - Craft