name: CommandLog
main: MineBlock\CommandLog\CommandLog
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 commandlog:
  permission: commandlog.cmd
  description: CommandLog
  usage: /CommandLog <View|Clear|AllClear>

permissions:
 commandlog.cmd:
  default: op
  description: CommandLog - Command