name: SubInventory
main: MineBlock\SubInventory\SubInventory
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 subinventory:
  permission: subinventory.cmd
  description: SubInventory - Command
  usage: /SubInventory

permissions:
 subinventory.cmd:
  default: true
  description: SubInventory - Command