name: CommandDebug
main: MineBlock\CommandDebug\CommandDebug
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 commanddebug:
  permission: commanddebug.cmd
  description: CommandDebug
  usage: /CommandDebug <Add|Del|Reset|List>
 
permissions:
 commanddebug.cmd:
  default: op
  description: CommandDebug - Command