name: TeleportView
main: MineBlock\TeleportView\TeleportView
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 teleportview:
  permission: teleportview.cmd
  description: TeleportView
  usage: /TeleportView

permissions:
 teleportview.cmd:
  default: op
  description: TeleportView - Command