name: ChatSwitch
main: MineBlock\ChatSwitch\ChatSwitch
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 chatswitch:
  permission: chatswitch.cmd
  description: ChatSwitch
  usage: /ChatSwitch

permissions:
 chatswitch.cmd:
  default: true
  description: ChatSwitch - Command