name: Delivery
main: MineBlock\Delivery\Delivery
version: "1.0"
api: [1.6.0]
author: MineBlock
description: MineBlock's Plugin
website: http://MineBlock.zz.am

commands:
 delivery:
  permission: delivery.cmd
  description: Delivery
  usage: /Delivery <PlayerName> <ItemID> <Amount>

permissions:
 delivery.cmd:
  default: true
  description: Delivery - Command